### ISSUE TITLE
Failed to load url /node_modules/@slidev/client/layoutHelper (resolved id: /Users/Easure/Desktop/slidev/自媒体平台运营计划及AI智能应用落地实物产品的探索/node_modules/@slidev/client/layoutHelper) in /Users/Easure/Desktop/slidev/自媒体平台运营计划及AI智能应用落地实物产品的探索/node_modules/slidev-theme-unicorn/layouts/cover-logos.vue. Does the file exist?

### ISSUE THREAD

**Issue by aihoom** [Dawntraoz/slidev-theme-unicorn#5]
It seems like there are some issues when using it.

**Comment by jrg94** [comment]
I get the same error. It seems the last time this theme worked was on version 0.37.x of slidev. I had been living in 0.31.x land for a while but wanted to make use of some of the newer features of slidev. I'll share some of the errors shortly when I get a chance, but even on <=0.37, I get the following warning:

```
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
```

**Comment by jrg94** [comment]
When I update to v0.38.x, I get an error about a dozen times in the following form:

```
Failed to load url .../node_modules/@slidev/client/constants (resolved id: .../node_modules/@slidev/client/constants) in .../node_modules/@slidev/client/App.vue. Does the file exist?
```

There's a similar error for layoutHelper in new-section.vue. Both errors persist in v0.39.x.

When upgrading to v0.40.x and v0.41.x, the errors for `constants` go away, and I'm left with just two instances of the layoutHelper error. Then, in v0.42.x, the layoutHelper error jumps up to five instances, which drops back down to four in v0.43.x and back up to five in v0.44.x. 

In versions v0.45.x and v0.46.x, the errors start to get fun. The error is fundamentally the same, but it also says interesting things like:

```
7:42:49 PM [vite] Pre-transform error: Failed to load url... (x6)
```

Then, in v0.47.x, the same error pops up eight times. And once we finally get to the latest version, v0.48.x, the error drops down to appearing only three times. All the while the warning from above persists. 

**You can ignore most of this deep dive**. I was mainly just trying to see if there was a somewhat newer version that worked. It looks like I'm stuck on v0.37.x. I think the main reason we can't update is because [v0.38.x](https://github.com/slidevjs/slidev/releases/tag/v0.38.0) introduces Vite 4, which must have some breaking changes. Interestingly, the errors change slightly in [v0.45.x](https://github.com/slidevjs/slidev/releases/tag/v0.45.0), which introduces Vite 5. If I knew anything about slidev themes, I would fork this and make the necessary changes. Regardless, hopefully this information helps someone come along and do that. I really love the theme!
